[package]
name = "Rusterminal"
version = "0.3.3-beta2"
edition = "2024"

[dependencies]
chrono = "0.4.41"
hostname = "0.4.1"
regex = "1.11.1"
rustc_version = "0.4.1"
rustc_version_runtime = "0.3.0"
rustyline = "16.0.0"
